# class Car:
#     def __init__(self, make, model, year):
#         self.make = make                       
#         self.model = model
#         self.year = year

#     def start(self):                           
#         print(f"The {self.make} {self.model} model will be starting year {self.year}  .")

#     def display_info(self):
#         print(f"\nCar Information:\n"
#               f"Make: {self.make}\n"
#               f"Model: {self.model}\n"
#               f"Year: {self.year}\n")


# Thar = Car(make="Thar", model="Top", year=2025)

# Thar.display_info()
# Thar.start()


# Car Class


# class Car:
#     def __init__(self, make, model, year):
#         self.make = make                       
#         self.model = model
#         self.year = year

#     def start(self):                           
#         print(f"The {self.make} {self.model} model will be starting year {self.year}.")

#     def display_info(self):
#         print(f"\nCar Information:\n"
#               f"Make: {self.make}\n"
#               f"Model: {self.model}\n"
#               f"Year: {self.year}\n")

# def factorial(n):
#     if n == 0:
#         return 1
#     else:
#         return n * factorial(n - 1)

# Thar = Car(make="Thar", model="Top", year=2025)
# Thar.display_info()
# Thar.start()
# num = 5 
# print(f"\nFactorial of {num}: {factorial(num)}")
